image: ufsm/ufsm-maven:latest

stages:
  - deploy
  
variables:
  KUBECTL_NAMESPACE: "default"
  DEPLOY_PATH: "/srv/"
  CNAME: "172.16.0.241:4000/"  
  
deploy site:
  stage: deploy
  script:
    - mkdir -p /root/.kube
    - cat "$KUBECTL_CONFIG" > /root/.kube/config
    - ID_CONTAINER=$(/var/opt/kubectl --namespace=$KUBECTL_NAMESPACE get pod | grep knowledge-base | cut -d' ' -f1)
    #- /var/opt/kubectl --namespace=$KUBECTL_NAMESPACE delete pod $ID_CONTAINER
    - /var/opt/kubectl --namespace=$KUBECTL_NAMESPACE  exec $ID_CONTAINER /var/opt/update.sh
  environment:
    name: knowledge-base
    url: http://${CNAME}




    
