image: ufsm/ufsm-maven:latest

stages:
  - deploy
  
variables:
  KUBECTL_NAMESPACE: "default"
  DEPLOY_PATH: "/srv/"
  CNAME: "172.16.0.241:4000/"  
  
deploy site:
  stage: deploy
  script:
    - mkdir -p /root/.kube
    - cat "$KUBECTL_CONFIG" > /root/.kube/config
    - /var/opt/kubectl --namespace=$KUBECTL_NAMESPACE delete -f knowledge-base-deployment.yml
    - sleep 10
    - /var/opt/kubectl --namespace=$KUBECTL_NAMESPACE create -f knowledge-base-deployment.yml
  environment:
    name: develop
    url: http://${CNAME}




    
