image: ufsm/ufsm-maven:latest

stages:
  - deploy
  
variables:
  KUBECTL_NAMESPACE: "default"
  DEPLOY_PATH: "/srv/"
  CNAME: "172.16.0.241:4000/"  
  
deploy site:
  stage: deploy
  script:
    - mkdir -p /root/.kube
    - cat "$KUBECTL_CONFIG" > /root/.kube/config
    - /var/opt/kubectl --namespace=$KUBECTL_NAMESPACE scale deployment ufsm-glassfish-dev1 --replicas=0
    - /var/opt/kubectl --namespace=$KUBECTL_NAMESPACE scale deployment ufsm-glassfish-dev1 --replicas=1
  environment:
    name: knowledge-base
    url: http://${CNAME}




    
